server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user_db
    username: postgres
    password: People
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
